### ISSUE TITLE
Fatal Error on Activation

### ISSUE THREAD

**Issue by jacobmcabee** [brendenplugin/chargebee-wp-membership-plugin#1]
![screen shot 2017-01-04 at 12 21 58 pm](https://cloud.githubusercontent.com/assets/17126510/21655737/77361e7e-d278-11e6-8386-15651bedc25c.png)

After downloading the repo as a .zip file, and attempting to install per the guide provided, I got the following error after attempting to activate the plugin.

> Plugin could not be activated because it triggered a fatal error.
> 
> Need Wordpress Version > 4.5.0

Site Info:

> WordPress Version: 4.7
> Current WordPress Theme: Twenty Sixteen version 1.3
> Theme Author: the WordPress team - https://wordpress.org/
> Theme URI: https://wordpress.org/themes/twentysixteen/
> Active Plugins: gravityforms/gravityforms.php | debug-info/debug-info.php | gravityformsstripe/stripe.php | gravityformsuserregistration/userregistration.php | 
> PHP Version: 5.6.29
> MySQL Version: 5.6.25-log
> Apache Version: This information is not available.

Looking forward to testing out the full functionality soon!

**Comment by brendenplugin** [comment]
Thank you for the detailed explanation. Thought that get_bloginfo() would return as  4.7.0 for version 4.7. It is fixed now.
