### ISSUE TITLE
Compatibility with Wordpress Core 4.7.1

### ISSUE THREAD

**Issue by jacobmcabee** [brendenplugin/chargebee-wp-membership-plugin#2]
I'm in the process of working out how to implement the plugin, and the account shortcode `[cb_account_link]Account[/cb_account_link]` has stopped working on both my sandbox and production sites.

For example: 
http://sr.newcreationgraphics.com/user-links/

The account link points to http://sr.newcreationgraphics.com/user-links/#, but no action appears to happen when it is clicked.

Test username: testingaccount
Test password: @CS%Ravi1SMTUh3ji(L*PgWT

The account has the Chargebee Member role, and is associated with a subscription when I look at the profile.

I'm guessing this is related to today's update to WordPress 4.7.1. Any ideas?

**Comment by CharanyaCB** [comment]
Hey Jacob!
The "Account" link works only for logged in users. Also, it is recommended not to share username and password on a public forum. Thanks.

**Comment by jacobmcabee** [comment]
It's resolved now. I believe it was due to an unknown issue with the WordPress automatic update. After I rolled back to 4.7.0 and ran the 4.7.1 update again, the issue seems to have been resolved, and the user account shortcode link is working again.

What's the preferred secure method for contacting the WordPress beta team? Should I call your main number or email your support address? Thanks!

**Comment by CharanyaCB** [comment]
Jacob, this plugin was released as an open source project mainly to allow contribution from everyone. If there's an issue, anyone who has the answer can post it here (it can be you guys, the third party, Chargebee or developers specialized in Wordpress). Our support team also has to check with the third party for plugin related queries, so the best way would be to file an issue here! This way, one of us will be able to answer them. :)

**Comment by jacobmcabee** [comment]
Thanks!
