### ISSUE TITLE
Getting error "Invalid API Key" on test site

### ISSUE THREAD

**Issue by accomplishtraining** [brendenplugin/chargebee-wp-membership-plugin#3]
FIXED! My original message below might help someone else trying this...I forgot to add -test to the chargebee site name.
--------------------------
Original Problem:
The API works on my Live site, but not the Test site. I notice the instructions said not to use the Live site, so I'm stuck, unless anyone has a suggestion?

Tried two different keys from test site. Both full access. Exact error message is: "Sorry, authentication failed. Invalid api key"

**Comment by brendenplugin** [comment]
Hey thanks for pointing out. As you already know, the LIVE and TEST sites are different according to Chargebee.
